// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phylet.Data;

#nullable disable

namespace Phylet.Data.Migrations
{
    [DbContext(typeof(PhyletDbContext))]
    [Migration("20260320125249_InitialDeviceConfiguration")]
    partial class InitialDeviceConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Phylet.Data.Configuration.DeviceConfigurationEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("DeviceConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
